/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      fontFamily: {
        'headline': ['Space Grotesk', 'sans-serif'],
        'body': ['Manrope', 'sans-serif'],
        'label': ['Space Grotesk', 'sans-serif'],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        // Custom colors from design
        tertiary: "#515f78",
        'secondary-fixed': "#ffdbcb",
        'on-tertiary-fixed-variant': "#39475f",
        'on-error': "#ffffff",
        'primary-fixed-dim': "#00daf3",
        'tertiary-fixed-dim': "#b9c7e4",
        'primary-fixed': "#9cf0ff",
        'surface-bright': "#f7f9fb",
        error: "#ba1a1a",
        'inverse-surface': "#2d3133",
        'on-tertiary-fixed': "#0d1c32",
        outline: "#6b7a7d",
        'on-secondary-fixed': "#341100",
        'surface-container-lowest': "#ffffff",
        'secondary-container': "#fd6c00",
        'surface-dim': "#d8dadc",
        'on-primary-container': "#00626e",
        'inverse-primary': "#00daf3",
        'on-tertiary': "#ffffff",
        'error-container': "#ffdad6",
        'primary-container': "#00e5ff",
        surface: "#f7f9fb",
        'on-secondary': "#ffffff",
        'surface-container-high': "#e6e8ea",
        'on-primary': "#ffffff",
        'on-surface-variant': "#3b494c",
        'surface-tint': "#006875",
        'on-primary-fixed': "#001f24",
        'on-error-container': "#93000a",
        'on-background': "#191c1e",
        'secondary-fixed-dim': "#ffb692",
        'surface-container-highest': "#e0e3e5",
        'inverse-on-surface': "#eff1f3",
        'on-secondary-container': "#562000",
        'outline-variant': "#bac9cc",
        'tertiary-container': "#c3d1ef",
        'on-surface': "#191c1e",
        'surface-container': "#eceef0",
        'tertiary-fixed': "#d6e3ff",
        'on-tertiary-container': "#4c5973",
        'on-secondary-fixed-variant': "#7a3000",
        secondary: "#9f4200",
        primary: "#006875",
        'surface-container-low': "#f2f4f6",
        'on-primary-fixed-variant': "#004f58",
        'surface-variant': "#e0e3e5"
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
